eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
          defaultZone: http://localhost:8761/eureka/
          
  
          
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost;instance=SQLEXPRESS;encrypt=true;trustServerCertificate=true;database=empDatails
    username: satibhaski
    password: Puja@1234
    
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql:  true
    
    properties:
      hibernate:
       dialect: org.hibernate.dialect.SQLServerDialect
            
         
